site_name: Dashboard de Datos Simple
repo_url: https://github.com/Martii03/Ejercicio_Streamlit
repo_name: Martii03/Ejercicio_Streamlit
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

nav:
  - Inicio: index.md
  - Aplicación: stapp.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Martii03/Ejercicio_Streamlit 